#!/usr/bin/env bash
# This Bash script that displays the content of the file /etc/passwd.
# Display:
#   username
#   user id
#   Home directory path for the user

while IFS=: read -r f1 _ f3 _ _ f6 _
do
    echo "$f1:$f3:$f6"
done < /etc/passwd
