#!/usr/bin/env bash
#this scripts test use case of until,if,elif statements
number=1
while [ "$number" -lt 11 ]; do
    if [ "$number" -eq 4 ]; then
        echo "bad luck"
    elif [ "$number" -eq 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi
    number=$((number + 1))
done
