#!/usr/bin/env bash
#this scripts is tag  the superstituion shid
number=1
while [ "$number" -lt 21 ]; do
    echo "$number"
    case $number in
    4)
        echo "bad luck from China"
        ;;
    9)
        echo "bad luck from Japan"
        ;;
    17)
        echo "bad luck from Italy"
        ;;
    esac

    number=$((number + 1))
done
